# Параметры пайплайна
threads: 8
memory: "40"

# Директории
input_dir: "data/raw"
output_dir: "results"

# Референс (опционально)
ref_genome: "data/ref/genome.fasta"

# Базы данных
kraken_db: "/path/to/kraken2_db"
busco_db: "vertebrata_odb10"
